version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
    env_file:
      - ../.env
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ..:/workspace
    working_dir: /workspace
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
    env_file:
      - ../.env
    command: celery -A api.celery_app.celery worker --loglevel=INFO
    volumes:
      - ..:/workspace
    working_dir: /workspace
    depends_on:
      - redis
      - db

  minio:
    image: minio/minio:RELEASE.2025-01-05T00-00-00Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata:
