from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    MISSING_IN_2B = "MISSING_IN_2B"
    INV_NO_MISMATCH = "INV_NO_MISMATCH"
    DATE_MISMATCH = "DATE_MISMATCH"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    TAX_SPLIT_MISMATCH = "TAX_SPLIT_MISMATCH"
    DUPLICATE_INVOICE = "DUPLICATE_INVOICE"
    INVALID_GSTIN = "INVALID_GSTIN"
    HSN_NON_COMPLIANT = "HSN_NON_COMPLIANT"
    DOC_TYPE_MISMATCH = "DOC_TYPE_MISMATCH"
    TABLE13_MISMATCH = "TABLE13_MISMATCH"

